### ISSUE TITLE
Normalizar banco de dados

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#1]
Realizar normalização em todas tabelas do banco de dados:

Turmas - @Thayno e @jokebede 
Homenageados - @EvelinNogueira e @JairLiao 
Cursos - @GideaoVieira e @LuisFernandoPL 
Formandos - @leolds88 

Segue script enviado pela @EvelinNogueira 

USE [master]
GO
/****** Object:  Database [EGRESSOS]    Script Date: 03/11/2016 21:23:14 ******/

CREATE DATABASE [EGRESSOS]
 
/****** Object:  Table [dbo].[CURSO]    Script Date: 03/11/2016 21:23:14 ******/

CREATE TABLE [dbo].[CURSO](
	[ID_CURSO] [int] NOT NULL,
	[NOME] [varchar](50) NULL,
	[DURACAO] [int] NULL,
 CONSTRAINT [PK_CURSO] PRIMARY KEY CLUSTERED 
(
	[ID_CURSO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[FORMANDOS]    Script Date: 03/11/2016 21:23:14 ******/
CREATE TABLE [dbo].[FORMANDOS](
	[ID_FORMANDO] [int] IDENTITY(1,1) NOT NULL,
	[ID_TURMA] [int] NULL,
	[NOME] [varchar](50) NULL,
	[CPF] [varchar](11) NULL,
	[DATA_NASCIMENTO] [date] NULL,
	[NATURALIDADE] [varchar](50) NULL,
	[EMAIL] [varchar](100) NULL,
	[FOTO] [varchar](500) NULL,
 CONSTRAINT [PK_FORMANDOS] PRIMARY KEY CLUSTERED 
(
	[ID_FORMANDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[HOMENAGEADOS]    Script Date: 03/11/2016 21:23:14 ******/

CREATE TABLE [dbo].[HOMENAGEADOS](
	[ID_HOMENAGEADOS] [int] NOT NULL,
	[ID_TURMA] [int] NULL,
	[NOME] [varchar](50) NULL,
	[NATURALIDADE] [varchar](50) NULL,
	[PROFISSAO] [varchar](50) NULL,
	[EMAIL] [varchar](100) NULL,
	[FOTO_HOMENAGEADOS] [varchar](100) NULL,
 CONSTRAINT [PK_HOMENAGEADOS] PRIMARY KEY CLUSTERED 
(
	[ID_HOMENAGEADOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[TURMAS]    Script Date: 03/11/2016 21:23:14 ******/

CREATE TABLE [dbo].[TURMAS](
	[ID_TURMA] [int] NOT NULL,
	[ID_CURSO] [int] NULL,
	[DATA_FORMATURA] [date] NULL,
	[FOTO_TURMA] [varchar](500) NULL,
 CONSTRAINT [PK_TURMAS] PRIMARY KEY CLUSTERED 
(
	[ID_TURMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[FORMANDOS]  WITH CHECK ADD  CONSTRAINT [FK_FORMANDOS_TURMAS] FOREIGN KEY([ID_TURMA])
REFERENCES [dbo].[TURMAS] ([ID_TURMA])
GO

ALTER TABLE [dbo].[FORMANDOS] CHECK CONSTRAINT [FK_FORMANDOS_TURMAS]
GO

ALTER TABLE [dbo].[TURMAS]  WITH CHECK ADD  CONSTRAINT [FK_TURMAS_CURSO] FOREIGN KEY([ID_CURSO])
REFERENCES [dbo].[CURSO] ([ID_CURSO])
GO

ALTER TABLE [dbo].[TURMAS] CHECK CONSTRAINT [FK_TURMAS_CURSO]
GO

ALTER TABLE [dbo].[TURMAS]  WITH CHECK ADD  CONSTRAINT [FK_TURMAS_HOMENAGEADOS] FOREIGN KEY([ID_TURMA])
REFERENCES [dbo].[HOMENAGEADOS] ([ID_HOMENAGEADOS])
GO

ALTER TABLE [dbo].[TURMAS] CHECK CONSTRAINT [FK_TURMAS_HOMENAGEADOS]
GO

USE [master]
GO

**Comment by Thayno** [comment]
Realizamos normalização!

**Comment by jokebede** [comment]
USE [EGRESSOS]
GO
/****** Object:  Table [dbo].[Turmas]    Script Date: 03/11/2016 22:37:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Turmas](
	[IdTurma] [int] NOT NULL,
	[DataFormatura] [varchar](50) NOT NULL,
	[FotoTurma] [varchar](500) NOT NULL,
	[IdCurso] [int] NOT NULL,
 CONSTRAINT [PK_TURMAS] PRIMARY KEY CLUSTERED 
(
	[IdTurma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Turmas]  WITH CHECK ADD  CONSTRAINT [FK_TURMAS_CURSOS] FOREIGN KEY([IdCurso])
REFERENCES [dbo].[CURSOS] ([ID_CURSO])
GO
ALTER TABLE [dbo].[Turmas] CHECK CONSTRAINT [FK_TURMAS_CURSOS]
GO

**Comment by jokebede** [comment]
Realizamos Normalização

**Comment by EvelinNogueira** [comment]
Conclui a normalização da tabela "Homenageados"

USE [EGRESSOS]
GO
/****** Object:  Table [dbo].[Homenageados]    Script Date: 03/11/2016 21:45:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Homenageados](
	[IdHomenageado] [int] NOT NULL,
	[IdTurma] [int] NULL,
	[Nome] [varchar](50) NULL,
	[Naturalidade] [varchar](50) NULL,
	[Profissao] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[FotoHomenageados] [varchar](100) NULL,
 CONSTRAINT [PK_HOMENAGEADOS] PRIMARY KEY CLUSTERED 
(
	[IdHomenageado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO

**Comment by leolds88** [comment]
Conclui a normalização da tabela "Formandos"


CREATE TABLE [dbo].[Formandos](
	[IDFormando] [int] IDENTITY(1,1) NOT NULL,
	[IDturma] [int] NULL,
	[Nome] [varchar](50) NULL,
	[CPF] [varchar](11) NULL,
	[DataNascimento] [date] NULL,
	[Naturalidade] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[Foto] [varchar](500) NULL,
 CONSTRAINT [PKFormandos] PRIMARY KEY CLUSTERED 
(
	[IDformando] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

**Comment by GideaoVieira** [comment]
conclui a normalização da tabela Cursos!!! 

CREATE TABLE [dbo].[Cursos](
	[IDCurso] [int] NOT NULL,
	[NomeCurso] [varchar](100) NOT NULL,
	[Duracao] [int] NOT NULL,
 CONSTRAINT [PK_CURSO] PRIMARY KEY CLUSTERED 
(
	[IDCurso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

**Comment by GideaoVieira** [comment]
Normalização da tabela "Cursos"
CREATE TABLE [dbo].[Cursos](
	[IDCurso] [int] NOT NULL,
	[NomeCurso] [varchar](100) NOT NULL,
	[Duracao] [int] NOT NULL,
 CONSTRAINT [PK_CURSO] PRIMARY KEY CLUSTERED 
(
	[IDCurso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
