### ISSUE TITLE
Criar Documentação: Apresentação do Sistema

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#10]
Criar apresentação comercial do sistema Portal Egresso, com pontos positivos e funcionalidades do sistema voltado para parte comercial.

Responsáveis: @Thayno e @JairLiao.

**Comment by Thayno** [comment]
Segue para o documento de 
[Apresentação do Sistema.docx](https://github.com/lucyanocm/portalEgressoFACIT/files/626060/Apresentacao.do.Sistema.docx)
Apresentação do Sistema @JairLiao e @Thayno !
