### ISSUE TITLE
Alterar texto da View [Home/Index]

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#2]
@jokebede e @EvelinNogueira 

Alterem os textos da view citada para algo como econtrado no link do site do curso na p[agina da FACIT http://www.faculdadefacit.edu.br/curso/26/curso-superior-de-tecnologia-em-analise-e-desenvolvimento-de-sistemas

**Comment by EvelinNogueira** [comment]
Adicionei mais uma view na pagina
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" >
                 <li>
                        <a href="">Mural dos Formandos</a>
                    </li>

**Comment by EvelinNogueira** [comment]
Foi adicionado mais uma view na pagina;
<li>
                        <a href="">Mural dos Formandos</a>
                    </li>
