### ISSUE TITLE
Criar CRUD para Homenageados Controller e Views

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#4]
Criar Controller para Homenageados com actions: Index, Adicionar, Excluir e Editar.

**Index** lista inicial de todos registros de homenageados contendo a opção de ir para editar ou excluir o registro.

**Adicionar** deve ter opção de enviar foto, fazendo salvamento da mesma na pasta "/img/homenageados/". O padrão para salvamento do arquivo deve ser **homenageado**+IdHomenageado, exemplo: "homenageado001.jpg". 

**Excluir** executar via JavaScript a action de remover o registro atual lembrando que é preciso validar se o registro não está relacionado com outra informação evitando problemas na exclusão.

**Editar** realiza opção de alterar um registro já existente, dando a opção de modificar todos os campos exceto Id.

Observação: Homenageados faz relacionamento com turmas portante essa relação deve ser mantida tanto na hora de adicionar quanto editar. 

Rota padrão para homenageados: ˜/Homenageados/{Action}

Responsáveis: @EvelinNogueira e @JairLiao .

**Comment by EvelinNogueira** [comment]
segue o id commit 02bd5634b74c8ab001a555976a25f3237fdc0135
