### ISSUE TITLE
Criar CRUD para Formandos, Controller e Views.

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#5]
Criar Controller para Formandos com actions: Index, Adicionar, Excluir e Editar.

**Index** lista inicial de todos registros de formandos contendo a opção de ir para editar ou excluir o registro.

**Adicionar** deve ter opção de enviar foto, fazendo salvamento da mesma na pasta "/img/formandos/". O padrão para salvamento do arquivo deve ser **formandos**+IdFormando, exemplo: "formandos001.jpg". 

**Excluir** executar via JavaScript a action de remover o registro atual lembrando que é preciso validar se o registro não está relacionado com outra informação evitando problemas na exclusão.

Rota padrão para Formandos: ˜/Formandos/{Action}

**Editar** realiza opção de alterar um registro já existente, dando a opção de modificar todos os campos exceto Id.

Observação: Formandos faz relacionamento com turmas portante essa relação deve ser mantida tanto na hora de adicionar quanto editar. 

Responsáveis: @leolds88 e @jokebede.

**Comment by leolds88** [comment]
finalizado segue o id 93630c6b4ce6fa6774180416d1edc90d558865e9
