### ISSUE TITLE
Criar CRUD para Turmas, Controller e Views

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#6]
Criar Controller para Turmas com actions: Index, Adicionar, Excluir e Editar.

**Index** lista inicial de todos registros de turmas contendo a opção de ir para editar ou excluir o registro.

**Adicionar** deve ter opção de enviar foto, fazendo salvamento da mesma na pasta "/img/turmas/". O padrão para salvamento do arquivo deve ser **turmas**+IdTurma, exemplo: "turma001.jpg". 

**Excluir** executar via JavaScript a action de remover o registro atual lembrando que é preciso validar se o registro não está relacionado com outra informação evitando problemas na exclusão.

Rota padrão para Turmas: ˜/Turmas/{Action}

**Editar** realiza opção de alterar um registro já existente, dando a opção de modificar todos os campos exceto Id.

Observação: Turmas faz relacionamento com cursos portante essa relação deve ser mantida tanto na hora de adicionar quanto editar. 

Responsáveis: @Thayno, @GideaoVieira e @LuisFernandoPL.

**Comment by GideaoVieira** [comment]
Finalizemos o CRUD de Turmas, segue o ID do Commit : 57be11bc9a29b37b9af5852699b3c364ebdf8957
