### ISSUE TITLE
Fotos da primeira turma de administração da FACIT

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#7]
Colocar anexo a essa Issues as fotos das primeira turma de formandos da FACIT.

CC: @EvelinNogueira

**Comment by EvelinNogueira** [comment]
![foto1](https://cloud.githubusercontent.com/assets/21184245/20457308/752ae394-ae6f-11e6-8839-e2e9020bc461.jpg)
![foto2](https://cloud.githubusercontent.com/assets/21184245/20457309/752b7d5e-ae6f-11e6-830c-f635c8fe0383.jpg)
![foto3](https://cloud.githubusercontent.com/assets/21184245/20457310/75303a10-ae6f-11e6-90c2-fc0f7163432f.jpg)
