### ISSUE TITLE
Criar documentação: Levantamento de Requisitos

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#8]
Criar documento do sistema Portal Egresso com o levantamento de requisitos de todo escopo do sistema.

Responsáveis: @leolds88, @EvelinNogueira e @jokebede.

**Comment by EvelinNogueira** [comment]
[Portal Egresso.docx](https://github.com/lucyanocm/portalEgressoFACIT/files/626130/Portal.Egresso.docx)
