### ISSUE TITLE
Criar documento: Diagrama de Entidade Relacionamento

### ISSUE THREAD

**Issue by lucyanocm** [lucyanocm/portalEgressoFACIT#9]
Criar documento DER com base no modelo do banco de dados já criado.

Observação: Comentar sobre todas tabelas e campos com seus respectivos usos.

Responsáveis: @GideaoVieira e @LuisFernandoPL.

**Comment by GideaoVieira** [comment]
[Trabalho Lucyano - DER.docx](https://github.com/lucyanocm/portalEgressoFACIT/files/628821/Trabalho.Lucyano.-.DER.docx)

Terminado DER. Gideão Vieira e Luis Fernando Paiva
